# Generated by Django 2.0.13 on 2022-04-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TSG', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='tsg',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
