# Generated by Django 2.0.13 on 2022-04-28 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TSG', '0005_auto_20220422_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('preview_text', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.CharField(blank=True, max_length=20, null=True)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('recipients', models.ManyToManyField(to='TSG.Flat')),
                ('tsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSG.Tsg')),
            ],
        ),
    ]
