# Generated by Django 2.0.13 on 2022-05-05 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSG', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('tsg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TSG.Tsg')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'region')},
        ),
        migrations.AddField(
            model_name='notification',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='TSG.NotificationSection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='notificationsection',
            unique_together={('tsg', 'name')},
        ),
    ]
