# Generated by Django 4.0.4 on 2022-05-29 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TSG', '0008_announcement_alter_city_id_alter_entrance_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='tsg',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='TSG.tsg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='users_viewed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='users_viewed',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
